# Generated by Django 4.0.5 on 2022-07-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('detalle', models.CharField(max_length=100, verbose_name='detalle')),
                ('icono', models.ImageField(null=True, upload_to='imagenes/', verbose_name='icono')),
            ],
        ),
    ]
