# Generated by Django 4.0.5 on 2022-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInterface', '0002_plususer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plususer',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='plususer',
            name='nick_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
