# Generated by Django 4.0.5 on 2022-07-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInterface', '0003_alter_plususer_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plususer',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
