# Generated by Django 4.0.5 on 2022-07-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInterface', '0004_alter_plususer_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plususer',
            name='foto_perfil',
            field=models.ImageField(default='imagenes/fotosperfil/foto perfil default.jpg', null=True, upload_to='imagenes/fotosperfil', verbose_name='foto_perfil'),
        ),
    ]
