# Generated by Django 4.0.5 on 2022-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNoticias', '0002_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
