# Generated by Django 4.0.5 on 2022-07-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNoticias', '0003_noticia_fecha_noticia_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
