# Generated by Django 4.0.5 on 2022-07-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNoticias', '0005_alter_noticia_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/', verbose_name='imagen'),
        ),
    ]
