# Generated by Django 4.0.5 on 2022-07-15 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppNoticias', '0006_alter_noticia_cuerpo_alter_noticia_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
